// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * Profile picture field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.profile_picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_picture: prismic.ImageField<never>;

  /**
   * Email field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone Number field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * Calendar field in *Author*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author.calendar_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  calendar_link: prismic.LinkField;

  /**
   * LinkedIn field in *Author*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author.linkedin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

type DeckDocumentDataSlicesSlice =
  | FeaturesSlice
  | TestimonialsSlice
  | ResourcesSlice
  | ReferencesSlice
  | AgendaSlice
  | ValuePropositionSlice
  | ProductSlice
  | MethodologySlice
  | LeadsGoalsSlice
  | IntroSlideSlice;

/**
 * Item in *Deck → Company domain*
 */
export interface DeckDocumentDataCompanyDomainItem {
  /**
   * Domain field in *Deck → Company domain*
   *
   * - **Field Type**: Text
   * - **Placeholder**: example : prismic.io
   * - **API ID Path**: deck.company_domain[].domain
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  domain: prismic.KeyTextField;
}

/**
 * Content for Deck documents
 */
interface DeckDocumentData {
  /**
   * Title field in *Deck*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deck.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Deck*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: deck.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DeckDocumentDataSlicesSlice> /**
   * Company name field in *Deck*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deck.company_name
   * - **Tab**: Config
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  company_name: prismic.KeyTextField;

  /**
   * Company Logo field in *Deck*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: deck.company_logo
   * - **Tab**: Config
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Company domain field in *Deck*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: deck.company_domain[]
   * - **Tab**: Config
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  company_domain: prismic.GroupField<
    Simplify<DeckDocumentDataCompanyDomainItem>
  >;

  /**
   * Author field in *Deck*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: deck.author
   * - **Tab**: Config
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author"> /**
   * Meta Description field in *Deck*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: deck.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Deck*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: deck.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Deck*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: deck.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField /**
   * Activate Password field in *Deck*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: deck.activate_password
   * - **Tab**: Access
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */;
  activate_password: prismic.BooleanField;

  /**
   * Password field in *Deck*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deck.password
   * - **Tab**: Access
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  password: prismic.KeyTextField;
}

/**
 * Deck document from Prismic
 *
 * - **API ID**: `deck`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DeckDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<DeckDocumentData>, "deck", Lang>;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Test field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.test
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  test: prismic.RichTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Prismic logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.prismic_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prismic_logo: prismic.ImageField<never>;

  /**
   * Prismic icon field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.prismic_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prismic_icon: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | AuthorDocument
  | DeckDocument
  | HomeDocument
  | SettingsDocument;

/**
 * Item in *Agenda → Default → Primary → Summary items*
 */
export interface AgendaSliceDefaultPrimarySummaryItemsItem {
  /**
   * Summary item name field in *Agenda → Default → Primary → Summary items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.summary_items[].summary_item_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  summary_item_name: prismic.RichTextField;
}

/**
 * Primary content in *Agenda → Default → Primary*
 */
export interface AgendaSliceDefaultPrimary {
  /**
   * Theme field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: agenda.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Title field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Summary items field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.summary_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  summary_items: prismic.GroupField<
    Simplify<AgendaSliceDefaultPrimarySummaryItemsItem>
  >;
}

/**
 * Default variation for Agenda Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AgendaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AgendaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Agenda*
 */
type AgendaSliceVariation = AgendaSliceDefault;

/**
 * Agenda Shared Slice
 *
 * - **API ID**: `agenda`
 * - **Description**: Agenda
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AgendaSlice = prismic.SharedSlice<"agenda", AgendaSliceVariation>;

/**
 * Item in *Features → Three Cols List → Primary → Features*
 */
export interface FeaturesSliceThreeColsListPrimaryFeaturesItem {
  /**
   * Icon field in *Features → Three Cols List → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsList.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Icon color field in *Features → Three Cols List → Primary → Features*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsList.primary.features[].icon_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon_color: prismic.SelectField<
    "orange" | "pink" | "green" | "purple" | "blue"
  >;

  /**
   * Title field in *Features → Three Cols List → Primary → Features*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsList.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Features → Three Cols List → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsList.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Cta Label field in *Features → Three Cols List → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsList.primary.features[].cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Cta Link field in *Features → Three Cols List → Primary → Features*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsList.primary.features[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Item in *Features → Three Cols Grid → Primary → Features*
 */
export interface FeaturesSliceThreeColsGridPrimaryFeaturesItem {
  /**
   * Icon field in *Features → Three Cols Grid → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsGrid.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Icon color field in *Features → Three Cols Grid → Primary → Features*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsGrid.primary.features[].icon_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon_color: prismic.SelectField<
    "orange" | "pink" | "green" | "purple" | "blue"
  >;

  /**
   * Title field in *Features → Three Cols Grid → Primary → Features*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsGrid.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Features → Three Cols Grid → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsGrid.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Feature Link field in *Features → Three Cols Grid → Primary → Features*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsGrid.primary.features[].feature_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  feature_link: prismic.LinkField;
}

/**
 * Primary content in *Features → TwoCols → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * Theme field in *Features → TwoCols → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: features.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *Features → TwoCols → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Features → TwoCols → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Features → TwoCols → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *Features → TwoCols → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * TwoCols variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Features → Three Cols List → Primary*
 */
export interface FeaturesSliceThreeColsListPrimary {
  /**
   * Theme field in *Features → Three Cols List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: features.threeColsList.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *Features → Three Cols List → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsList.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Features → Three Cols List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsList.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Features field in *Features → Three Cols List → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsList.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<FeaturesSliceThreeColsListPrimaryFeaturesItem>
  >;
}

/**
 * Three Cols List variation for Features Slice
 *
 * - **API ID**: `threeColsList`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceThreeColsList = prismic.SharedSliceVariation<
  "threeColsList",
  Simplify<FeaturesSliceThreeColsListPrimary>,
  never
>;

/**
 * Primary content in *Features → Three Cols Grid → Primary*
 */
export interface FeaturesSliceThreeColsGridPrimary {
  /**
   * Theme field in *Features → Three Cols Grid → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: features.threeColsGrid.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *Features → Three Cols Grid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsGrid.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Features → Three Cols Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsGrid.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Features field in *Features → Three Cols Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsGrid.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<FeaturesSliceThreeColsGridPrimaryFeaturesItem>
  >;

  /**
   * Cta Label field in *Features → Three Cols Grid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsGrid.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Cta Link field in *Features → Three Cols Grid → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.threeColsGrid.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Three Cols Grid variation for Features Slice
 *
 * - **API ID**: `threeColsGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceThreeColsGrid = prismic.SharedSliceVariation<
  "threeColsGrid",
  Simplify<FeaturesSliceThreeColsGridPrimary>,
  never
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation =
  | FeaturesSliceDefault
  | FeaturesSliceThreeColsList
  | FeaturesSliceThreeColsGrid;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Item in *IntroSlide → 3 groups → Primary → Logos*
 */
export interface IntroSlideSliceDefaultPrimaryLogosItem {
  /**
   * Group Name field in *IntroSlide → 3 groups → Primary → Logos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.default.primary.logos[].group_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_name: prismic.KeyTextField;

  /**
   * Logo 1 field in *IntroSlide → 3 groups → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.default.primary.logos[].logo_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_1: prismic.ImageField<never>;

  /**
   * Logo 2 field in *IntroSlide → 3 groups → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.default.primary.logos[].logo_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_2: prismic.ImageField<never>;

  /**
   * Logo 3 field in *IntroSlide → 3 groups → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.default.primary.logos[].logo_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_3: prismic.ImageField<never>;

  /**
   * Logo 4 field in *IntroSlide → 3 groups → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.default.primary.logos[].logo_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_4: prismic.ImageField<never>;

  /**
   * Logo 5 field in *IntroSlide → 3 groups → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.default.primary.logos[].logo_5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_5: prismic.ImageField<never>;

  /**
   * Logo 6 field in *IntroSlide → 3 groups → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.default.primary.logos[].logo_6
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_6: prismic.ImageField<never>;
}

/**
 * Item in *IntroSlide → Single Group of logos → Primary → Logos*
 */
export interface IntroSlideSliceSingleGroupPrimaryLogosItem {
  /**
   * Logo field in *IntroSlide → Single Group of logos → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.singleGroup.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *IntroSlide → 3 groups → Primary*
 */
export interface IntroSlideSliceDefaultPrimary {
  /**
   * Theme field in *IntroSlide → 3 groups → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: intro_slide.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Title field in *IntroSlide → 3 groups → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *IntroSlide → 3 groups → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Logos field in *IntroSlide → 3 groups → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<Simplify<IntroSlideSliceDefaultPrimaryLogosItem>>;
}

/**
 * 3 groups variation for IntroSlide Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroSlideSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroSlideSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *IntroSlide → Single Group of logos → Primary*
 */
export interface IntroSlideSliceSingleGroupPrimary {
  /**
   * Theme field in *IntroSlide → Single Group of logos → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: intro_slide.singleGroup.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Title field in *IntroSlide → Single Group of logos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.singleGroup.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *IntroSlide → Single Group of logos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.singleGroup.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Logos field in *IntroSlide → Single Group of logos → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_slide.singleGroup.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<
    Simplify<IntroSlideSliceSingleGroupPrimaryLogosItem>
  >;
}

/**
 * Single Group of logos variation for IntroSlide Slice
 *
 * - **API ID**: `singleGroup`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroSlideSliceSingleGroup = prismic.SharedSliceVariation<
  "singleGroup",
  Simplify<IntroSlideSliceSingleGroupPrimary>,
  never
>;

/**
 * Slice variation for *IntroSlide*
 */
type IntroSlideSliceVariation =
  | IntroSlideSliceDefault
  | IntroSlideSliceSingleGroup;

/**
 * IntroSlide Shared Slice
 *
 * - **API ID**: `intro_slide`
 * - **Description**: IntroSlide
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroSlideSlice = prismic.SharedSlice<
  "intro_slide",
  IntroSlideSliceVariation
>;

/**
 * Item in *LeadsGoals → With Image grid → Primary → Grid*
 */
export interface LeadsGoalsSliceWithImageGridPrimaryGridItem {
  /**
   * Image field in *LeadsGoals → With Image grid → Primary → Grid*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withImageGrid.primary.grid[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *LeadsGoals → With image → Primary*
 */
export interface LeadsGoalsSliceDefaultPrimary {
  /**
   * Theme field in *LeadsGoals → With image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: leads_goals.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *LeadsGoals → With image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *LeadsGoals → With image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *LeadsGoals → With image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *LeadsGoals → With image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * With image variation for LeadsGoals Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadsGoalsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LeadsGoalsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *LeadsGoals → With Image grid → Primary*
 */
export interface LeadsGoalsSliceWithImageGridPrimary {
  /**
   * Theme field in *LeadsGoals → With Image grid → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: leads_goals.withImageGrid.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *LeadsGoals → With Image grid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withImageGrid.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *LeadsGoals → With Image grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withImageGrid.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *LeadsGoals → With Image grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withImageGrid.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *LeadsGoals → With Image grid → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withImageGrid.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Grid field in *LeadsGoals → With Image grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withImageGrid.primary.grid[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grid: prismic.GroupField<
    Simplify<LeadsGoalsSliceWithImageGridPrimaryGridItem>
  >;
}

/**
 * With Image grid variation for LeadsGoals Slice
 *
 * - **API ID**: `withImageGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadsGoalsSliceWithImageGrid = prismic.SharedSliceVariation<
  "withImageGrid",
  Simplify<LeadsGoalsSliceWithImageGridPrimary>,
  never
>;

/**
 * Primary content in *LeadsGoals → With Image and Illustration → Primary*
 */
export interface LeadsGoalsSliceWithImageAndIllustrationPrimary {
  /**
   * Theme field in *LeadsGoals → With Image and Illustration → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: leads_goals.withImageAndIllustration.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *LeadsGoals → With Image and Illustration → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withImageAndIllustration.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *LeadsGoals → With Image and Illustration → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withImageAndIllustration.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *LeadsGoals → With Image and Illustration → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withImageAndIllustration.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *LeadsGoals → With Image and Illustration → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withImageAndIllustration.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Illustration field in *LeadsGoals → With Image and Illustration → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withImageAndIllustration.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Illustration Background Color field in *LeadsGoals → With Image and Illustration → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: leads_goals.withImageAndIllustration.primary.illustration_background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  illustration_background_color: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;
}

/**
 * With Image and Illustration variation for LeadsGoals Slice
 *
 * - **API ID**: `withImageAndIllustration`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadsGoalsSliceWithImageAndIllustration =
  prismic.SharedSliceVariation<
    "withImageAndIllustration",
    Simplify<LeadsGoalsSliceWithImageAndIllustrationPrimary>,
    never
  >;

/**
 * Primary content in *LeadsGoals → With Illustration → Primary*
 */
export interface LeadsGoalsSliceWithIllustrationPrimary {
  /**
   * Theme field in *LeadsGoals → With Illustration → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: leads_goals.withIllustration.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *LeadsGoals → With Illustration → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withIllustration.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *LeadsGoals → With Illustration → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withIllustration.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *LeadsGoals → With Illustration → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withIllustration.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Illustration field in *LeadsGoals → With Illustration → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: leads_goals.withIllustration.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Illustration Background Color field in *LeadsGoals → With Illustration → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: leads_goals.withIllustration.primary.illustration_background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  illustration_background_color: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;
}

/**
 * With Illustration variation for LeadsGoals Slice
 *
 * - **API ID**: `withIllustration`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadsGoalsSliceWithIllustration = prismic.SharedSliceVariation<
  "withIllustration",
  Simplify<LeadsGoalsSliceWithIllustrationPrimary>,
  never
>;

/**
 * Slice variation for *LeadsGoals*
 */
type LeadsGoalsSliceVariation =
  | LeadsGoalsSliceDefault
  | LeadsGoalsSliceWithImageGrid
  | LeadsGoalsSliceWithImageAndIllustration
  | LeadsGoalsSliceWithIllustration;

/**
 * LeadsGoals Shared Slice
 *
 * - **API ID**: `leads_goals`
 * - **Description**: LeadsGoals
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadsGoalsSlice = prismic.SharedSlice<
  "leads_goals",
  LeadsGoalsSliceVariation
>;

/**
 * Item in *Methodology → Intro → Primary → Users*
 */
export interface MethodologySliceDefaultPrimaryUsersItem {
  /**
   * User field in *Methodology → Intro → Primary → Users*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodology.default.primary.users[].user
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  user: prismic.KeyTextField;
}

/**
 * Primary content in *Methodology → Intro → Primary*
 */
export interface MethodologySliceDefaultPrimary {
  /**
   * Theme field in *Methodology → Intro → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: methodology.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Title field in *Methodology → Intro → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: methodology.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Methodology → Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodology.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Methodology → Intro → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: methodology.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Users field in *Methodology → Intro → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: methodology.default.primary.users[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  users: prismic.GroupField<Simplify<MethodologySliceDefaultPrimaryUsersItem>>;
}

/**
 * Intro variation for Methodology Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MethodologySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MethodologySliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Methodology → User → Primary*
 */
export interface MethodologySliceUserPrimary {
  /**
   * Theme field in *Methodology → User → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: methodology.user.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * User number field in *Methodology → User → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodology.user.primary.user_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  user_number: prismic.KeyTextField;

  /**
   * Title field in *Methodology → User → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: methodology.user.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * User color field in *Methodology → User → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: pink
   * - **API ID Path**: methodology.user.primary.user_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  user_color: prismic.SelectField<"pink" | "blue" | "green", "filled">;

  /**
   * Description field in *Methodology → User → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodology.user.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Methodology → User → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: methodology.user.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Media side field in *Methodology → User → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: methodology.user.primary.media_side
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  media_side: prismic.BooleanField;
}

/**
 * User variation for Methodology Slice
 *
 * - **API ID**: `user`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MethodologySliceUser = prismic.SharedSliceVariation<
  "user",
  Simplify<MethodologySliceUserPrimary>,
  never
>;

/**
 * Slice variation for *Methodology*
 */
type MethodologySliceVariation = MethodologySliceDefault | MethodologySliceUser;

/**
 * Methodology Shared Slice
 *
 * - **API ID**: `methodology`
 * - **Description**: Methodology
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MethodologySlice = prismic.SharedSlice<
  "methodology",
  MethodologySliceVariation
>;

/**
 * Primary content in *Product → Default → Primary*
 */
export interface ProductSliceDefaultPrimary {
  /**
   * Theme field in *Product → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: product.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *Product → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Product → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Product → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Product → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Product Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Product*
 */
type ProductSliceVariation = ProductSliceDefault;

/**
 * Product Shared Slice
 *
 * - **API ID**: `product`
 * - **Description**: Product
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductSlice = prismic.SharedSlice<
  "product",
  ProductSliceVariation
>;

/**
 * Primary content in *References → Two Cols Text → Primary*
 */
export interface ReferencesSliceDefaultPrimary {
  /**
   * Theme field in *References → Two Cols Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: references.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Company logo field in *References → Two Cols Text → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: references.default.primary.company_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Title field in *References → Two Cols Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: references.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *References → Two Cols Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: references.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Right Side Content field in *References → Two Cols Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: references.default.primary.right_side_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  right_side_content: prismic.RichTextField;
}

/**
 * Two Cols Text variation for References Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReferencesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReferencesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *References → With Image → Primary*
 */
export interface ReferencesSliceWithImagePrimary {
  /**
   * Theme field in *References → With Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: references.withImage.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Company logo field in *References → With Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: references.withImage.primary.company_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Title field in *References → With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: references.withImage.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *References → With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: references.withImage.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *References → With Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: references.withImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Bottom Content field in *References → With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: references.withImage.primary.bottom_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_content: prismic.RichTextField;
}

/**
 * With Image variation for References Slice
 *
 * - **API ID**: `withImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReferencesSliceWithImage = prismic.SharedSliceVariation<
  "withImage",
  Simplify<ReferencesSliceWithImagePrimary>,
  never
>;

/**
 * Slice variation for *References*
 */
type ReferencesSliceVariation =
  | ReferencesSliceDefault
  | ReferencesSliceWithImage;

/**
 * References Shared Slice
 *
 * - **API ID**: `references`
 * - **Description**: References
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReferencesSlice = prismic.SharedSlice<
  "references",
  ReferencesSliceVariation
>;

/**
 * Primary content in *Resources → Default → Primary*
 */
export interface ResourcesSliceDefaultPrimary {
  /**
   * Theme field in *Resources → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: resources.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Title field in *Resources → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resources.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Resources → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resources.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Resources Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResourcesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ResourcesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Resources → Contact → Primary*
 */
export interface ResourcesSliceContactPrimary {
  /**
   * Theme field in *Resources → Contact → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: resources.contact.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Title field in *Resources → Contact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resources.contact.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Contact variation for Resources Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResourcesSliceContact = prismic.SharedSliceVariation<
  "contact",
  Simplify<ResourcesSliceContactPrimary>,
  never
>;

/**
 * Slice variation for *Resources*
 */
type ResourcesSliceVariation = ResourcesSliceDefault | ResourcesSliceContact;

/**
 * Resources Shared Slice
 *
 * - **API ID**: `resources`
 * - **Description**: Resources
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResourcesSlice = prismic.SharedSlice<
  "resources",
  ResourcesSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Testimonials*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * Author picture field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].author_picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_picture: prismic.ImageField<never>;

  /**
   * Author Name field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].author_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Role and Company field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].author_role_and_company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_role_and_company: prismic.KeyTextField;

  /**
   * Testimonial field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testimonial: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Theme field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: testimonials.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Testimonials field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Testimonials → Single Testimonial → Primary*
 */
export interface TestimonialsSliceSingleTestimonialPrimary {
  /**
   * Theme field in *Testimonials → Single Testimonial → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: testimonials.singleTestimonial.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Author picture field in *Testimonials → Single Testimonial → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.singleTestimonial.primary.author_picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_picture: prismic.ImageField<never>;

  /**
   * Author Name field in *Testimonials → Single Testimonial → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.singleTestimonial.primary.author_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Role and Company field in *Testimonials → Single Testimonial → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.singleTestimonial.primary.author_role_and_company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_role_and_company: prismic.KeyTextField;

  /**
   * Testimonial field in *Testimonials → Single Testimonial → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.singleTestimonial.primary.testimonial
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testimonial: prismic.RichTextField;
}

/**
 * Single Testimonial variation for Testimonials Slice
 *
 * - **API ID**: `singleTestimonial`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceSingleTestimonial = prismic.SharedSliceVariation<
  "singleTestimonial",
  Simplify<TestimonialsSliceSingleTestimonialPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation =
  | TestimonialsSliceDefault
  | TestimonialsSliceSingleTestimonial;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Item in *ValueProposition → Two Columns With Logos → Primary → Logos*
 */
export interface ValuePropositionSliceTwoColumnsWithLogosPrimaryLogosItem {
  /**
   * Logo field in *ValueProposition → Two Columns With Logos → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.twoColumnsWithLogos.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Item in *ValueProposition → With List → Primary → List*
 */
export interface ValuePropositionSliceWithListPrimaryListItem {
  /**
   * List item field in *ValueProposition → With List → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.withList.primary.list[].list_item
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_item: prismic.RichTextField;

  /**
   * List icon field in *ValueProposition → With List → Primary → List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.withList.primary.list[].list_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  list_icon: prismic.ImageField<never>;
}

/**
 * Primary content in *ValueProposition → TwoColumns → Primary*
 */
export interface ValuePropositionSliceDefaultPrimary {
  /**
   * Theme field in *ValueProposition → TwoColumns → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: value_proposition.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *ValueProposition → TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *ValueProposition → TwoColumns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ValueProposition → TwoColumns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *ValueProposition → TwoColumns → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * TwoColumns variation for ValueProposition Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValuePropositionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ValuePropositionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ValueProposition → Two Columns With Diagram → Primary*
 */
export interface ValuePropositionSliceTwoColumnsWithDiagramPrimary {
  /**
   * Theme field in *ValueProposition → Two Columns With Diagram → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: value_proposition.twoColumnsWithDiagram.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *ValueProposition → Two Columns With Diagram → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.twoColumnsWithDiagram.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *ValueProposition → Two Columns With Diagram → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.twoColumnsWithDiagram.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ValueProposition → Two Columns With Diagram → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.twoColumnsWithDiagram.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *ValueProposition → Two Columns With Diagram → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.twoColumnsWithDiagram.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Two Columns With Diagram variation for ValueProposition Slice
 *
 * - **API ID**: `twoColumnsWithDiagram`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValuePropositionSliceTwoColumnsWithDiagram =
  prismic.SharedSliceVariation<
    "twoColumnsWithDiagram",
    Simplify<ValuePropositionSliceTwoColumnsWithDiagramPrimary>,
    never
  >;

/**
 * Primary content in *ValueProposition → Two Columns With Logos → Primary*
 */
export interface ValuePropositionSliceTwoColumnsWithLogosPrimary {
  /**
   * Theme field in *ValueProposition → Two Columns With Logos → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: value_proposition.twoColumnsWithLogos.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *ValueProposition → Two Columns With Logos → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.twoColumnsWithLogos.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *ValueProposition → Two Columns With Logos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.twoColumnsWithLogos.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ValueProposition → Two Columns With Logos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.twoColumnsWithLogos.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *ValueProposition → Two Columns With Logos → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.twoColumnsWithLogos.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Logos field in *ValueProposition → Two Columns With Logos → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.twoColumnsWithLogos.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<
    Simplify<ValuePropositionSliceTwoColumnsWithLogosPrimaryLogosItem>
  >;
}

/**
 * Two Columns With Logos variation for ValueProposition Slice
 *
 * - **API ID**: `twoColumnsWithLogos`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValuePropositionSliceTwoColumnsWithLogos =
  prismic.SharedSliceVariation<
    "twoColumnsWithLogos",
    Simplify<ValuePropositionSliceTwoColumnsWithLogosPrimary>,
    never
  >;

/**
 * Primary content in *ValueProposition → With List → Primary*
 */
export interface ValuePropositionSliceWithListPrimary {
  /**
   * Theme field in *ValueProposition → With List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Slide theme color
   * - **Default Value**: white
   * - **API ID Path**: value_proposition.withList.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "white" | "orange" | "pink" | "green" | "purple" | "blue",
    "filled"
  >;

  /**
   * Eyebrow field in *ValueProposition → With List → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.withList.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *ValueProposition → With List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.withList.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ValueProposition → With List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.withList.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * List field in *ValueProposition → With List → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.withList.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<
    Simplify<ValuePropositionSliceWithListPrimaryListItem>
  >;
}

/**
 * With List variation for ValueProposition Slice
 *
 * - **API ID**: `withList`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValuePropositionSliceWithList = prismic.SharedSliceVariation<
  "withList",
  Simplify<ValuePropositionSliceWithListPrimary>,
  never
>;

/**
 * Slice variation for *ValueProposition*
 */
type ValuePropositionSliceVariation =
  | ValuePropositionSliceDefault
  | ValuePropositionSliceTwoColumnsWithDiagram
  | ValuePropositionSliceTwoColumnsWithLogos
  | ValuePropositionSliceWithList;

/**
 * ValueProposition Shared Slice
 *
 * - **API ID**: `value_proposition`
 * - **Description**: ValueProposition
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValuePropositionSlice = prismic.SharedSlice<
  "value_proposition",
  ValuePropositionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AuthorDocument,
      AuthorDocumentData,
      DeckDocument,
      DeckDocumentData,
      DeckDocumentDataSlicesSlice,
      DeckDocumentDataCompanyDomainItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      AgendaSlice,
      AgendaSliceDefaultPrimarySummaryItemsItem,
      AgendaSliceDefaultPrimary,
      AgendaSliceVariation,
      AgendaSliceDefault,
      FeaturesSlice,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceThreeColsListPrimaryFeaturesItem,
      FeaturesSliceThreeColsListPrimary,
      FeaturesSliceThreeColsGridPrimaryFeaturesItem,
      FeaturesSliceThreeColsGridPrimary,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      FeaturesSliceThreeColsList,
      FeaturesSliceThreeColsGrid,
      IntroSlideSlice,
      IntroSlideSliceDefaultPrimaryLogosItem,
      IntroSlideSliceDefaultPrimary,
      IntroSlideSliceSingleGroupPrimaryLogosItem,
      IntroSlideSliceSingleGroupPrimary,
      IntroSlideSliceVariation,
      IntroSlideSliceDefault,
      IntroSlideSliceSingleGroup,
      LeadsGoalsSlice,
      LeadsGoalsSliceDefaultPrimary,
      LeadsGoalsSliceWithImageGridPrimaryGridItem,
      LeadsGoalsSliceWithImageGridPrimary,
      LeadsGoalsSliceWithImageAndIllustrationPrimary,
      LeadsGoalsSliceWithIllustrationPrimary,
      LeadsGoalsSliceVariation,
      LeadsGoalsSliceDefault,
      LeadsGoalsSliceWithImageGrid,
      LeadsGoalsSliceWithImageAndIllustration,
      LeadsGoalsSliceWithIllustration,
      MethodologySlice,
      MethodologySliceDefaultPrimaryUsersItem,
      MethodologySliceDefaultPrimary,
      MethodologySliceUserPrimary,
      MethodologySliceVariation,
      MethodologySliceDefault,
      MethodologySliceUser,
      ProductSlice,
      ProductSliceDefaultPrimary,
      ProductSliceVariation,
      ProductSliceDefault,
      ReferencesSlice,
      ReferencesSliceDefaultPrimary,
      ReferencesSliceWithImagePrimary,
      ReferencesSliceVariation,
      ReferencesSliceDefault,
      ReferencesSliceWithImage,
      ResourcesSlice,
      ResourcesSliceDefaultPrimary,
      ResourcesSliceContactPrimary,
      ResourcesSliceVariation,
      ResourcesSliceDefault,
      ResourcesSliceContact,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceSingleTestimonialPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TestimonialsSliceSingleTestimonial,
      ValuePropositionSlice,
      ValuePropositionSliceDefaultPrimary,
      ValuePropositionSliceTwoColumnsWithDiagramPrimary,
      ValuePropositionSliceTwoColumnsWithLogosPrimaryLogosItem,
      ValuePropositionSliceTwoColumnsWithLogosPrimary,
      ValuePropositionSliceWithListPrimaryListItem,
      ValuePropositionSliceWithListPrimary,
      ValuePropositionSliceVariation,
      ValuePropositionSliceDefault,
      ValuePropositionSliceTwoColumnsWithDiagram,
      ValuePropositionSliceTwoColumnsWithLogos,
      ValuePropositionSliceWithList,
    };
  }
}
